config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #ルートを選択画面に設定する。
  root "auths#show"

  # auths controller
  resource :auths do
    get 'logout'
    get 'mypage'
  end

  # rooms controller
  resources :rooms
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  #ログイン認証
  before_action :basic_auth, only: [:mypage]
  #ログアウト処理
  before_action :empty_auth, only: [:logout]

  #showメソッドはログインとアカウント作成を選択する画面を表示する。
  def show
  end
  # ログイン情報を上書き
  def logout
  end
  #新規ユーザの登録
  def new
    #フォームへの入力で以下の宣言が必要
    @user = User.new
  end
  # ログインを検証しマイページを表示する。
  def mypage
    @user = session[:user]
  end

  #POST時に生じる処理。
  #情報の登録
  def create
    #ユーザを作成
    user = User.new(user_info)
    #同一ユーザを検索して表示。同一名のユーザは存在を許さないため必ず0 or 1つのレコードが検出される。
    user_exist = User.find_by(user_name: user.user_name, password: user.password)
    #もしすでに同一名のユーザが存在した場合。ログインホームにリダイレクトする。
    return redirect_to url_for action: 'mypage' unless user_exist.nil?
    #偽認証の情報と同一の場合、失敗するように設定する。入力し直しのためにnew画面に戻す。
    return redirect_to url_for action: 'new' if user.user_name.eql?("WT5CZXGqkwLuv05D")
    
    #ユーザ名に対応するひとり言ルームを同時に作成する。
    room = Room.new(room_name: user.user_name)
    #新規ユーザの場合データベースに登録する。
    if user.save && room.save
      #登録に成功した場合、登録してマイページに移動する。
      session[:user] = user
      #中間テーブルに追加する
      room.users << user
      #認証情報をヘッダに付与してリダイレクトする。
      redirect_to url_for(action: 'mypage', only_path: false, user: user.user_name, password: user.password)
    else
      #失敗した場合、入力画面に戻る。
      redirect_to url_for action: 'new'
    end
  end

  #公開しない処理の定義
  private
  #POST時のPOST内容を表示する
  def user_info
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/views/auths/_form.html.erb
<%= form_with model: user, url: path_to_post do |f| %>
    <div>
        <div>
        ユーザ名 (１文字以上１６文字未満の半角英数字)
        </div>
        <%= f.text_field :user_name %>
    </div>
    <br>
    <div>
        <div>
        パスワード (１文字以上１６文字未満の半角英数字)
        </div>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.submit '登録' %>
    </div>
<% end %>

app/views/auths/logout.html.erb
<h1>ログアウトしたページ</h1>


<br />
<%= link_to 'ホームへ', url_for(action: 'show',only_path: false)  %>

app/views/auths/mypage.html.erb
<h1>マイページ</h1>

<div>
    <p>
        こんにちわ<%= @user.user_name %>さん。
    </p>

    <%= link_to 'チャットルーム一覧へ移動', controller: 'rooms', action: 'index' %>
    <br />
    <br />
    <%= link_to 'ログアウトします', url_for(action: 'logout',only_path: false, user: 'WT5CZXGqkwLuv05D', password: 'WT5CZXGqkwLuv05D') %>
</div>

app/views/auths/new.html.erb
<h1>アカウント登録</h1>

<%= render 'auths/form', user: @user, path_to_post: auths_url %>

app/views/auths/show.html.erb
<h1>FlowChat</h1>

<div>
    <p>FlowChatにようこそ</p>
    <p>このサイトはフローチャート機能を取り入れたチャットアプリです。</p>
    <p>（注：現在開発中。フローチャート機能未実装）</p>
    <p>現在以下の機能を実装しています。</p>
    <ol>
        <li>ひとり言機能（ひとりでチャットを使います）</li>
    </ol>
</div>
<br />
<div>
    <p>アカウントを持っている方はログインしてください</p>
    <%= link_to 'ログインする',url_for(action: 'mypage',only_path: false, user: '', password: '') %>
</div>
<br />
<div>
    <p>アカウントを持っていない人は作成してください。</p>
    <%= link_to 'アカウントを作成します', url_for(action: 'new',only_path: false, user: '', password: '') %>
</div>